### ISSUE TITLE
Turkish Language Support

### ISSUE THREAD

**Issue by emresaracoglu** [maxmind/GeoIP2-php#101]
Hello,

Thank you for your service, I like it but I cant change to my language (Turkish)

`print($record->country->names['tr-TR'] . "\n");`

> Notice: Undefined index: tr-TR in ...

How can I provide Turkish language?

**Comment by oschwald** [comment]
Unfortunately, we don't provide Turkish in the database. However, you can look up the Turkish names using the `geoname_id` along with the data set from [GeoNames](http://www.geonames.org/). This is the same dataset we use for the locales we do include.

**Comment by emresaracoglu** [comment]
I see, thank you for your answer.
