### ISSUE TITLE
IP Address (IPv4) not found error

### ISSUE THREAD

**Issue by thapame** [maxmind/GeoIP2-php#102]
Some IP's does not seems to be working (e.g.: 162.159.24.224) and throwing Address Not Found Exception.

I thought maxmind covers all publicly available IP addresses (https://support.maxmind.com/geoip-faq/geoip2-and-geoip-legacy-databases/how-much-of-the-ip-address-space-do-you-cover/)

**Comment by oschwald** [comment]
Thanks for raising this. The database indeed does not have a record for that address. The FAQ entry is a bit misleading as the database only provides location information for publicly routable addresses that we believe to be _active_ with some specific exclusions. In this case, it appears that the IP address appears to be a Cloudflare anycast address, which is excluded.

In any case, this isn't an API bug so I am closing the issue. Please follow up with [support@maxmind.com](mailto:support@maxmind.com) if you have further questions.
