### ISSUE TITLE
Fatal error when IP not found

### ISSUE THREAD

**Issue by jcbenton** [maxmind/GeoIP2-php#105]
Hi,

I quickly found out while testing the GeoIP2-php code that it produces a fatal error when an IP is not found. I of course have built in some code to prevent feeding it any IP that should not be in the database:

filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_RES_RANGE | FILTER_FLAG_NO_PRIV_RANGE)

Of course, there is no guarantee that one particular legitimate IP may not be found in the database. Maxmind says that "most" IPv6 addresses are included. This is not ALL and thus there is room for a fatal error. 

Regardless of what you feed this, in my opinion, it should never produce a fatal error. This stops all execution. I'd like to suggest that the code be updated so that only a warning is thrown and a NULL value is returned instead. GeoIP is usually only a small part of a much larger set of code. It shouldn't crash the train.

**Comment by oschwald** [comment]
This library throws a structured exception that can be caught. It does not invoke a fatal error.

**Comment by jcbenton** [comment]
What's this ? It stops the entire script, so it is fatal. You can't catch fatal errors. Or am I missing something?

`PHP Fatal error:  Uncaught GeoIp2\Exception\AddressNotFoundException: The address 10.10.10.10 is not in the database.`

**Comment by jcbenton** [comment]
Or is it the fact the error was not caught that makes it fatal?

**Comment by oschwald** [comment]
An exception becomes fatal when you don't catch it. You can catch it with something like:

```
    try {
        $city = $reader->city($ip);
    } catch (AddressNotFoundException $e) {
        // Your handling of the not-found case here.
    }
```

**Comment by jcbenton** [comment]
Yeah. I was starting to figure that out when I read your first reply. Thanks.

**Comment by borzaka** [comment]
I did this as a fallback when saving country names and later count the unique ones.
```
try {
	$geoip = $reader->country($clientip->lastip);
	$country_name = $geoip->country->name;
} catch (GeoIp2\Exception\AddressNotFoundException $e) {
	$country_name = 'UNKNOWN';
}

array_push($country_names, $country_name);
```
