### ISSUE TITLE
[SOLVED] Fatal error:  Class 'GeoIp2\Database\Reader' not found

### ISSUE THREAD

**Issue by jshrek** [maxmind/GeoIP2-php#106]
I am receving the following error:
`Fatal error:  Class 'GeoIp2\Database\Reader' not found`

Here is my code using PHP, but I can not figure out what I am doing wrong as I have correctly required the .phar file (v2.7.0) and that does not throw an error.

```
function geo_get_continent($ip) {
	require_once __DIR__."/geoip2.phar";
	$reader = new GeoIp2\Database\Reader(__DIR__."/maxmind-geoip2/GeoLite2-Country.mmdb"); //NOTE: also tried with slash in front  new \GeoIp2\Database\Reader but got same error.
	$record = $reader->country($ip);
	$continent = $record->continent->code;
	return $continent;
}
```

**Comment by jshrek** [comment]
SOLVED: It turns out the PHAR extension was not enabled on PHP.

When I required the phar file, it did not throw any errors or warnings so I assumed it was enabled.

Since I could not figure out how to enable the PHAR extension on shared hosting, I instead extracted all the files from the PHAR file, uploaded them, and then used:
`require_once __DIR__."/geoip2/vendor/autoload.php"; //Instead of PHAR`

And all works good now.

**Comment by oschwald** [comment]
Good to hear that you resolved this! I'll close the issue.
