### ISSUE TITLE
How I get TimeZone of User

### ISSUE THREAD

**Issue by emresaracoglu** [maxmind/GeoIP2-php#111]
Hello,

How to detect user's timezone with GeoIP? It's possbile?

**Comment by nchelluri** [comment]
Hi @emresaracoglu,

As long as you're not using the Country database, it is possible. See `$timeZone` on http://maxmind.github.io/GeoIP2-php/doc/v2.8.0/class-GeoIp2.Record.Location.html .

> This record is returned by all location services and databases besides Country.

A general overview is available at https://dev.maxmind.com/faq/how-can-i-determine-the-timezone-of-a-website-visitor/ .

Thanks!

**Comment by emresaracoglu** [comment]
Thank you for your answer @nchelluri
		

		
	_____________________________

**Comment by emresaracoglu** [comment]
I use city database and I can not get out.

print($record->time->zone);

is not it true?

**Comment by emresaracoglu** [comment]
I use city database and I can not get out.

print($record->time->zone);

is not it true?

cc @nchelluri

**Comment by nchelluri** [comment]
I think you want `print($record->location->timeZone);`.

**Comment by emresaracoglu** [comment]
Thank you for your time again.
@nchelluri
