### ISSUE TITLE
List of region codes and names

### ISSUE THREAD

**Issue by sgiehl** [maxmind/GeoIP2-php#112]
For GeoIP Legacy you had provided a csv (https://www.maxmind.com/download/geoip/misc/region_codes.csv) to be able to get the region name based on the region code. 
As GeoIP2 now uses ISO codes for all regions, this list can't be used anymore. Do you provide a new list with those mappings for GeoIP2?

**Comment by oschwald** [comment]
We don't supply this data ourselves beyond what is in the database file, which does include the names for a lookup. If you want a straight mapping between subdivision ISO codes and names, I would suggest looking at [GeoNames](http://www.geonames.org/).

**Comment by sgiehl** [comment]
Ok. Thanks for the answer. One last question. Might all region codes included in `GeoLite2-City-Locations-en.csv` be returned? If seen that the [old region codes for France](https://en.wikipedia.org/wiki/ISO_3166-2:FR#Former_metropolitan_regions_(before_January_1st,_2016)) are (still) included. Is that only for "backwards compatibility" or might they still be returned?

**Comment by oschwald** [comment]
If they show up in that CSV, they are still returned. I would suggest contacting [support@maxmind.com](mailto:support@maxmind.com) about data quality issues.
