### ISSUE TITLE
geoip2.phar 2.9.0 on PHP 7.1

### ISSUE THREAD

**Issue by seltix5** [maxmind/GeoIP2-php#118]
When testing geoip2.phar 2.9.0 on PHP 7.1 the script just exit... i'm unable to get any error log
PHP :
```
before
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

include(__DIR__ . '/MaxMind-GeoIP2/geoip2.phar');
?>
after

```
On PHP 7.2 it works normally...

Any help? Thanks!

**Comment by oschwald** [comment]
I am not sure why you aren't getting an error logged. You could check that Phar support is enabled with:

```
php -m | grep Phar
```

**Comment by seltix5** [comment]
hello,
yes I do have Phar support :

> braldesi@cp70 [~]# php -m | grep Phar
> Phar

I'm using PHP 7.1.20 and the script just stops on include().
When using php 7.2 it works as expected... there is nothing else to debug?
Thanks

**Comment by oschwald** [comment]
It is hard to say without knowing more about your environment(s). I would try using the Composer installation instructions instead.

**Comment by seltix5** [comment]
I do not use composer since I dont have shell access to my server...
there is nothing else I can test? It works with PHP 7.2, it should work with 7.1 right?

**Comment by oschwald** [comment]
You don't need shell access to use Composer. You can just upload your vendor directory. I'd check your server logs, if you can. In particular, parse errors may not be displayed despite your above script.
