### ISSUE TITLE
Access Maxmind API using User ID and License Key

### ISSUE THREAD

**Issue by Vikram0811** [maxmind/GeoIP2-php#119]
In order to authenticate with the City Webservice API, can we append the userid and license_key parameter to the API's base URL and set it to our access key value.

For example - https://geoip.maxmind.com/geoip/v2.1/city/{ip_address}?userid=YourUserID&license_key=YourLicenseKey

The JSON response can be fetched and later utilized as per requirement

Thanks

**Comment by oschwald** [comment]
If you are not using this API, I would suggest contacting support@maxmind.com. However, for this particular question, you must use basic auth. You cannot pass the account ID and license key as params.

**Comment by Vikram0811** [comment]
Hey,

I do not want to use the Client API but make API calls directly for city webservice. I do have maxmind account id and license key. How can I use basic auth for this?

Thanks
