### ISSUE TITLE
GeoIP2.phar 2.9.0 don't work with Joomla > 3.9.2

### ISSUE THREAD

**Issue by jurihahn** [maxmind/GeoIP2-php#129]
https://github.com/joomla/joomla-cms/issues/24176
https://github.com/TYPO3/phar-stream-wrapper/issues/21
https://github.com/TYPO3/phar-stream-wrapper/pull/22

**Comment by oschwald** [comment]
From those issues, it isn't clear to me that this is a bug in `geoip2.phar` as opposed to the Phar loader that is being used. If you could provide a simple standalone test case, that would be helpful.

However, as mentioned in the documentation, using a Phar is discouraged. It is recommended that you install this with Composer.

**Comment by jurihahn** [comment]
I described how to reproduce this error: https://github.com/joomla/joomla-cms/issues/23907

**Comment by oschwald** [comment]
According to the discussion there, It appears that https://github.com/TYPO3/phar-stream-wrapper/pull/15 was supposed to fix this. Is this not the case? This seems outside of our control. Again, I would recommend not using the Phar at all.

**Comment by jurihahn** [comment]
Maybe you can pack the other packer PHAR.
Here it is described that you can work around this error:
https://github.com/TYPO3/phar-stream-wrapper/issues/21#issuecomment-473685969
But I did not succeed.

**Comment by jurihahn** [comment]
i have workaround:
`require_once ( 'phar://' . __DIR__ . '/geoip2.phar/vendor/autoload.php' );`

**Comment by oschwald** [comment]
Closing as this doesn't seem to be related to anything in particular about our Phar. It looks like the Phar loader in question has fixed the issue.
