### ISSUE TITLE
Ability to mock/pass custom web service client

### ISSUE THREAD

**Issue by atymic** [maxmind/GeoIP2-php#131]
Currently, the Web Service [Client Class](https://github.com/maxmind/GeoIP2-php/blob/master/src/WebService/Client.php) does not offer any way to inject or mock the web service client.

This would be useful for testing purposes.

Let me know if you'd accept a PR :)

**Comment by oschwald** [comment]
What did you have in mind in particular?

I am unsure about allowing injection of a mock `MaxMind\WebService\Client`. The reason for this is that this was created before PSR-7 was standardized and implemented by most clients. Ideally, I would like to see `MaxMind\WebService\Client` be PSR-7 compliant and allow the use of _any_ PSR-7 client. Allowing the injection of something with the same interface as the current client will create a dependency on its interface in third party code.

If the proposal is to provide an interface for `GeoIp2\WebService\Client`, I think that could work without the same concern.
