### ISSUE TITLE
phar 2.9.0 error with latest GeoLite2-City.mmdb

### ISSUE THREAD

**Issue by morrow95** [maxmind/GeoIP2-php#132]
Been using this for years now.  Decided to update the GeoLite2-City.mmdb the other day.  Downloaded from http://dev.maxmind.com/geoip/geoip2/geolite2/.  The size locally is showing 59,810kb with a date of 7/15/2019 @ 1:58pm (little smaller in size than the previous version I was using).

I didn't think anything of it till today when I saw these in the error log :

```
[22-Jul-2019 15:41:48 UTC] PHP Fatal error:  Uncaught MaxMind\Db\Reader\InvalidDatabaseException: Error opening database file (/home/example/public_html/assets/geoip/GeoLite2-City.mmdb). Is this a valid MaxMind DB file? in phar:///home/example/public_html/assets/geoip/2.9.0/geoip2.phar/vendor/maxmind-db/reader/src/MaxMind/Db/Reader.php:263
Stack trace:
#0 phar:///home/example/public_html/assets/geoip/2.9.0/geoip2.phar/vendor/maxmind-db/reader/src/MaxMind/Db/Reader.php(65): MaxMind\Db\Reader->findMetadataStart('/home/example...')
#1 phar:///home/example/public_html/assets/geoip/2.9.0/geoip2.phar/src/Database/Reader.php(53): MaxMind\Db\Reader->__construct('/home/example...')
#2 /home/example/public_html/somelink.php(80): GeoIp2\Database\Reader->__construct('/home/example...')
#3 {main}
  thrown in phar:///home/example/public_html/assets/geoip/2.9.0/geoip2.phar/vendor/maxmind-db/reader/src/MaxMind/Db/Reader.php on line 263
```

I reverted back to the previous version of GeoLite2-City.mmdb I was using and everything is fine again.  Not sure if maybe this is just a corrupt version that MaxMind uploaded or maybe they changed the format in some way and the 2.9.0 phar isn't handling it correctly.

Also, and I'm not sure if it is related, but I am getting a 500 error for the releases page here at https://github.com/maxmind/GeoIP2-php/releases which seems odd too.

**Comment by klp2** [comment]
Were you able to checked the md5sum of the downloaded tarball to see if it is correct? It looks like it should be `5ffbe767c2b8eda43f78d576f9d019ad`. When I download that tarball I end up with an MMDB file with a slightly different size, so I wonder if something went sideways during the download process. I'm not aware of any change in format of the MMDB file itself. If you have `mmdblookup` installed you might also be able to try a manual lookup to see if you get any results. If not, I would suggest trying download it again.

For the releases page 500, it looks like github has had some issues today that are still on-going, though I'm able to bring up that page now.

**Comment by morrow95** [comment]
MD5 matches up to the .tar.gz so according to that the .mmdb should be fine after extracting, but gives the error I mentioned above.

**Comment by klp2** [comment]
So far I'm unable to replicate this. This week's build of the GeoLite2-City database should now be available. When you have a chance, can you try that and see if you run into similar issues?

**Comment by oschwald** [comment]
Closing this as we were unable to replicate it and because it sounds like a bad file rather than an issue with this reader in particular.
