### ISSUE TITLE
Error on Phar file

### ISSUE THREAD

**Issue by gittyuserron** [maxmind/GeoIP2-php#135]
I get the following error on website :  1535198703 - Unexpected file extension in "phar://geoip2.phar/vendor/composer/../../src/Database/Reader.php"
I've re-downloaded current file, but no difference. Please help

**Comment by oschwald** [comment]
I'd recommend not using the Phar and using Composer instead. I don't know if you are using Drupal or something else that uses `typo3/phar-stream-wrapper`, but your problem sounds very similar to [this issue](https://www.drupal.org/project/drupal/issues/3026443).

**Comment by gittyuserron** [comment]
thanks for the response, I'm using joomla. Not sure how to use composer.

**Comment by oschwald** [comment]
What version of Joomla are you running? I believe this is fixed in the most recent release.

**Comment by gittyuserron** [comment]
Joomla 3.9.5

**Comment by oschwald** [comment]
Looking at the changes for the release, I think this should be fixed in 3.9.10. I am going to close this.
