### ISSUE TITLE
Support Github Actions as ci

### ISSUE THREAD

**Issue by Smolevich** [maxmind/GeoIP2-php#144]
Do you have plans to support Github Actions as ci?

**Comment by oschwald** [comment]
We don't have any immediate plans to migrate away from Travis. Is there a particular reason why you are asking?

**Comment by Smolevich** [comment]
Github Actions has some advantages over travis

**Comment by oschwald** [comment]
Yes, I agree. However, we are unlikely to switch until we have a particular need for that additional functionality or we need to rework the CI on this repo for another reason. We have many repos and switching them all to GitHub Actions or some other solution would be a fairly decent sized project.
