### ISSUE TITLE
geoip:update fails with composer

### ISSUE THREAD

**Issue by steveilyo** [maxmind/GeoIP2-php#145]
Sorry if this is an obvious question, but... 

We are using the geoip2/geoip2 composer install and PHP artisan. This fails with a;

[ErrorException] get_headers(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known  

could this be due to the implementation of key authentication  and if so where do we set our key?

**Comment by oschwald** [comment]
What exactly are you doing that is failing? The error message doesn't sound particularly related to this library.

**Comment by steveilyo** [comment]
OK, we are doing further investigation. I will get back to you with specifics, but the system has been running automatic build with GIT pipes and just started to fail when running;

composer install --no-interaction --no-progress --prefer-dist
> php artisan geoip:update
Updating...
                                                                                                             
  [ErrorException]                                                                                           
  get_headers(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known  
                                                                                                           
Script php artisan geoip:update handling the post-install-cmd event returned with error code 1

Hence us looking towards this library in conjunction with MaxMind now implements a key to update with their service.

**Comment by oschwald** [comment]
This library doesn't provide `geoip:update`. It sounds like you are using https://github.com/Torann/laravel-geoip. I'd suggest following up with them.

**Comment by steveilyo** [comment]
Many Apologies, my Bad... 🤗
