### ISSUE TITLE
File not working; HTTP 500 

### ISSUE THREAD

**Issue by rtwk** [maxmind/GeoIP2-php#146]
This is the code : 
`<?php
$ip = $_SERVER['REMOTE_ADDR'];
require_once 'vendor/autoload.php';
use GeoIp2\Database\Reader;

// This creates the Reader object, which should be reused across
// lookups.
$reader = new Reader('/usr/local/share/GeoIP/GeoIP2-City.mmdb');

// Replace "city" with the appropriate method for your database, e.g.,
// "country".
$record = $reader->city($ip);

print($record->city->name . "\n"); ?>`

vendor is in the same folder where this file resides. It is within /var/www/html/. It returns HTTP 500. What is missing?

**Comment by oschwald** [comment]
I would suggest checking your server logs for the exception text. Without those, it is hard to say what could be wrong. Perhaps the path to the database is incorrect.

**Comment by rtwk** [comment]
Does this repository contains the database? Or it has to be downloaded / purchased separately?

**Comment by oschwald** [comment]
We provide [free GeoLite2 databases](https://dev.maxmind.com/geoip/geoip2/geolite2/). There are more accurate [GeoIP2 databases](https://www.maxmind.com/en/geoip2-services-and-databases) available for purchase.

**Comment by rtwk** [comment]
Now when I purchased database and the code looks like this : 
`<?php
require_once 'vendor/autoload.php';
use GeoIp2\Database\Reader;
$ip = $_SERVER['REMOTE_ADDR'];
// This creates the Reader object, which should be reused across
// lookups.
$reader = new Reader('/var/www/html/GeoIP2-City-Asia-Pacific.mmdb');

// Replace "city" with the appropriate method for your database, e.g.,
// "country".
$record = $reader->city($ip);
print($record->city->name . "\n"); // 'Minneapolis'
?>`
The page does not return any output. The page works though. What may go wrong?
