### ISSUE TITLE
API does not print City name 

### ISSUE THREAD

**Issue by rtwk** [maxmind/GeoIP2-php#147]
Now when I purchased database and the code looks like this :
`<?php
require_once 'vendor/autoload.php';
use GeoIp2\Database\Reader;
$ip = $_SERVER['REMOTE_ADDR'];
// This creates the Reader object, which should be reused across
// lookups.
$reader = new Reader('/var/www/html/GeoIP2-City-Asia-Pacific.mmdb');

// Replace "city" with the appropriate method for your database, e.g.,
// "country".
$record = $reader->city($ip);
print($record->city->name . "\n"); 
?>`
The page does not return any output. The page works though. What may go wrong?

**Comment by oschwald** [comment]
I would suggest contacting [support@maxmind.com](mailto:support@maxmind.com). They should be able to help you diagnose the issue.
