### ISSUE TITLE
Not compatible with PHP 7.0

### ISSUE THREAD

**Issue by cleoni** [maxmind/GeoIP2-php#148]
Hello, 
I tried to follow the instructions and to execute the code below:

`<?php
	require 'vendor/autoload.php';
	use GeoIp2\Database\Reader;

	
// This creates the Reader object, which should be reused across lookups
$reader = new Reader('/xampp/htdocs/testodbc1/lib/geolite2/GeoIP2-City.mmdb');

// Replace "city" with the appropriate method for your database, e.g.,
// "country".
$record = $reader->city('213.209.220.102');

print($record->country->isoCode . "\n"); 
`

but I get

Parse error: syntax error, unexpected '=' in D:\xampp\htdocs\testodbc1\vendor\maxmind-db\reader\src\MaxMind\Db\Reader.php on line 99

it seems that the required MaxMind dB class uses often a syntax that's valid from php 7.4 onwards:

`[$metadataArray] = $metadataDecoder->decode($start);`

I thought it was better to tell, because on the front page the stated requirements say PHP 5.6 but it seems to be PHP 7.4 because of this.

**Comment by oschwald** [comment]
How are you installing your dependencies? Although it is true that the latest version of `maxmind-db/reader` requires PHP 7.2, the latest release of this package doesn't require that version. Composer should be picking a version of the dependency that works with the PHP you have installed. Perhaps you are running Composer with one PHP version but trying to use the package with another?
