### ISSUE TITLE
Breaking changes are being delivered in minor versions

### ISSUE THREAD

**Issue by gnumoksha** [maxmind/GeoIP2-php#151]
Hello. Version [2.11.0](https://github.com/maxmind/GeoIP2-php/releases/tag/v2.11.0) was released with two breaking changes:

- IMPORTANT: PHP 7.2 or greater is now required.
- Additional type hints have been added.

But according to [semver](https://semver.org/) one can update the minor version in the scenario where
> you add functionality in a backwards compatible manner,

**Comment by oschwald** [comment]
This is related to [this SemVer issue](https://github.com/semver/semver/issues/468). For the versioning of our libraries, we have followed the practice of not doing a major version bump when removing support for end of lifed language versions when the library's API has not changed. In the case of PHP, Composer is quite capable at only pulling in versions of a library that support the specified language version.

As for the type hints, I can see the argument there if the use is explicitly setting `strict_types`, although the types are the same as we have documented and in most cases another type would have failed previously anyway.

**Comment by gnumoksha** [comment]
> [...] although the types are the same as we have documented and in most cases another type would have failed previously anyway.

I don't think `most cases` are acceptable in a weakly typed language, but I will close this issue as I think this will come to nothing.

**Comment by oschwald** [comment]
Is there a particular case where you were passing in a value that is no longer accepted? It is a bit hard to discuss this in the abstract.

The only case that I have come across is passing in a null value for the locales parameter. This would kind of work previously, although significant functionality would be broken, e.g., the `name` methods for country, city, etc.
