### ISSUE TITLE
 php version dependency

### ISSUE THREAD

**Issue by crainday** [maxmind/GeoIP2-php#153]
![image](https://user-images.githubusercontent.com/19772479/96221062-73713780-0fbc-11eb-9689-5c01f1f54f99.png)
geoIp depends on extension maxmind-db/reader ~1.0
but maxmind-db/reader require php version >=7.2
![image](https://user-images.githubusercontent.com/19772479/96222684-496d4480-0fbf-11eb-8ffa-8ab303b9d9a7.png)

so geoIp cannot run in an environment lower than php7.2

**Comment by oschwald** [comment]
How are you installing? Older versions of `maxmind-db/reader` do support older versions of PHP and Composer should install an appropriate version. For instance, I just ran this using PHP 5.6:

```
$ php5.6 composer.phar require geoip2/geoip2:~2.0
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing composer/ca-bundle (1.2.8): Loading from cache
  - Installing maxmind/web-service-common (v0.7.0): Loading from cache
  - Installing maxmind-db/reader (v1.6.0): Downloading (100%)         
  - Installing geoip2/geoip2 (v2.10.0): Loading from cache
maxmind-db/reader suggests installing ext-bcmath (bcmath or gmp is required for decoding larger integers with the pure PHP decoder)
maxmind-db/reader suggests installing ext-maxminddb (A C-based database decoder that provides significantly faster lookups)
Writing lock file
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
```
