### ISSUE TITLE
Php8 support?

### ISSUE THREAD

**Issue by alfredone270895** [maxmind/GeoIP2-php#163]
i try to install in php8 i receive this error
Problem 1

wyrihaximus/html-compress 1.4.0 requires php ^7.0 || ^5.6 -> your PHP version (8.0.3) does not satisfy that requirement.
wyrihaximus/html-compress 1.4.0 requires php ^7.0 || ^5.6 -> your PHP version (8.0.3) does not satisfy that requirement.
wyrihaximus/html-compress 1.4.0 requires php ^7.0 || ^5.6 -> your PHP version (8.0.3) does not satisfy that requirement.
Installation request for wyrihaximus/html-compress (locked at 1.4.0) -> satisfiable by wyrihaximus/html-compress[1.4.0].

**Comment by oschwald** [comment]
`wyrihaximus/html-compress` is not a dependency of this package.

**Comment by alfredone270895** [comment]
yes excuse me is perfectly working i remove the unused package excuse me for bothering you , and thanks
