### ISSUE TITLE
Moodle 3.11.2 - maxmind 2.11.0 - Exception - the address is not in the database

### ISSUE THREAD

**Issue by elizadim** [maxmind/GeoIP2-php#166]
Hello,

after a system upgrade of our Moodle server, maxmind is throwing this error message and nothing we have done seems to be able to resolve the issue. So far, we have downloaded a new fresh copy of GeoLite city DB, reinstalled Maxmind completely as per the instructions in the readme file. Still getting the same error message on different actions: Exception - The address x.x.x.x is not in the database.

Turning debugging on give these error details: 
line 234 of /lib/maxmind/GeoIp2/Database/Reader.php: GeoIp2\Exception\AddressNotFoundException thrown
line 203 of /lib/maxmind/GeoIp2/Database/Reader.php: call to GeoIp2\Database\Reader->getRecord()
line 73 of /lib/maxmind/GeoIp2/Database/Reader.php: call to GeoIp2\Database\Reader->modelFor()
line 41 of /iplookup/lib.php: call to GeoIp2\Database\Reader->city()
line 217 of /lib/classes/antivirus/scanner.php: call to iplookup_find_location()
line 123 of /lib/classes/antivirus/manager.php: call to core\antivirus\scanner->get_incident_details()
line 144 of /repository/upload/lib.php: call to core\antivirus\manager::scan_file()
line 63 of /repository/upload/lib.php: call to repository_upload->process_upload()
line 328 of /repository/repository_ajax.php: call to repository_upload->upload()

Any help would be greatly appreciated!!

**Comment by elizadim** [comment]
I should also add that this happens for every user that has admin access, on any computer - of course,  the IP changes. This issue is not present on our other Moodle server running on 3.8.9

**Comment by oschwald** [comment]
I am not familiar with the Moodle integration. I would suggest contacting the author of that.

The exception is [documented](https://github.com/maxmind/GeoIP2-php#usage). The integration should be catching it and doing something reasonable given that there is no information for the IP.

As far as why it might be happening on one server and not your other servers, I'd guess that private IP addresses are getting passed to the GeoIP2 call. Perhaps you need to adjust your handling of the `X-Forwarded-For` or similar headers or perhaps this server's hosting situation is different in some way.
