### ISSUE TITLE
Error message: The application may only be invoked from a command line, got "fpm-fcgi"

### ISSUE THREAD

**Issue by dark-rider** [maxmind/GeoIP2-php#174]
When I replace geoip2.phar version 2.11.0 by 2.12.0, the following error message appears instead of the desired PHP website:
The application may only be invoked from a command line, got "fpm-fcgi"

How to fix this?

**Comment by oschwald** [comment]
Thanks. We upgraded our version of Box that generates the Phar file in the 2.12.0 release. This was an unintended side effect. 2.12.1 should be out shortly with a fix.

**Comment by oschwald** [comment]
2.12.1 has been released with the fix. Thanks!

**Comment by mrcblt** [comment]
I tried to use the 2.12.1 release together with the Geoblocker plugin within my own Nextcloud instance, and it still does not work. The Nextcloud protocol shows the following message:

`require_once(): Failed opening required 'phar://geoip2.phar/vendor/autoload.php'`

**Comment by oschwald** [comment]
@mrcblt, this sounds like a separate issue. I was able to reproduce the initial issues and I no longer experience it. It would make sense to open a separate issue along with steps on how we can reproduce it. Also, please confirm if 2.11.0 worked in this manner.

**Comment by mrcblt** [comment]
2.11.0 works fine. I will open a separate issue with a bit more details.

**Comment by mrcblt** [comment]
I just copied it back and forth and now it works. Sorry for the inconvenience.

**Comment by oschwald** [comment]
Great!
