### ISSUE TITLE
geoip2.phar 2.12.1: PHP website does not work

### ISSUE THREAD

**Issue by dark-rider** [maxmind/GeoIP2-php#178]
After geoip2.phar 2.12.0 used with PHP produced the error message: The application may only be invoked from a command line, got "fpm-fcgi", the fixed version 2.12.1 produces just an empty white page when 2.11.0 is replaced by 2.12.1.

The new way to generate the .phar file seems not yet to be compatible to version 2.11.0 and not yet tested sufficiently. So I unfortunately can only recommend to keep version 2.11.0.

**Comment by oschwald** [comment]
Have you checked your server log for an error? If you could do that and provide more information about the PHP environment this is running under, that would be very useful in understanding what is going one.

**Comment by dark-rider** [comment]
Ther log file shows HTTP error code 500.

**Comment by oschwald** [comment]
It sounds like you are looking at the access log. There should be an error log that contains information about the particular error that caused the 500.

**Comment by dark-rider** [comment]
I'm sorry, there are no more detailed logs.

**Comment by oschwald** [comment]
Unfortunately, I don't think there is much that we can do without the error log. Perhaps another user will have similar issues and have access to the error logs.

**Comment by dark-rider** [comment]
Maybe there has to be changed something within the PHP code after updating the PHAR file from 2.11.0 to 2.12.1?
`include_once 'geoip2.phar';
use GeoIp2\Database\Reader;
$geoip2_reader = new Reader('GeoLite2-City.mmdb');

$geoip_unknown = false;
try
{
	$geoip2_record = $geoip2_reader->city($_SERVER['REMOTE_ADDR']);
}
catch (GeoIp2\Exception\AddressNotFoundException $e)
{
	$geoip_unknown = true;
}
$geoip2_reader->close();

if($geoip_unknown)
	$geoip_result = "XX/XX/XX";
else
	$geoip_result = utf8_decode($geoip2_record->city->names['de']."/".$geoip2_record->mostSpecificSubdivision->names['de']."/".$geoip2_record->country->isoCode);
`

**Comment by dark-rider** [comment]
Maybe I have the same problem as another user in #179 (https://github.com/maxmind/GeoIP2-php/issues/179), because in the code quoted above, I shortened away an internal, different folder path for the PHAR and the MMDB file which both together are in a different folder than the PHP file?

So until 2.11.0 this was no problem, but from 2.12.1 on? The new way to generate the PHAR file may cause several unexpected side effects?

**Comment by oschwald** [comment]
Would you please test 2.12.2 to see if it fixes your issue?

**Comment by dark-rider** [comment]
2.12.2 is finally working - thank you very much, Gregory, and also to Eduardo from #179!

**Comment by oschwald** [comment]
Great! Thanks for confirming.
