### ISSUE TITLE
Change Phar Stub to allow different path

### ISSUE THREAD

**Issue by EduRuizDK** [maxmind/GeoIP2-php#179]
Please change Phar Stub to allow loading from different path:

Current stub (only works if geoip2.phar and script are in the same directory):
`<?php require_once 'phar://geoip2.phar/vendor/autoload.php'; __HALT_COMPILER(); ?>`

**Change to:**
`<?php require_once 'phar://' . __FILE__ . '/vendor/autoload.php'; __HALT_COMPILER(); ?>`

**Comment by oschwald** [comment]
Thanks for the report! 2.12.2 has been released with this fix.
