### ISSUE TITLE
GeoIp2\Database\Reader sometimes returns AddressNotFoundException

### ISSUE THREAD

**Issue by nag381** [maxmind/GeoIP2-php#192]
Hi,

I love your package and it has helped me a lot in my projects.
I am facing an issue where GeoIp2\Database\Reader sometimes returns AddressNotFoundException on live environment other times it returns the correct IP information. I am using maxmind database for IP lookup.

I have created a test function that dds the GeoIp2\Database\Reader instance:
`$reader = new Reader(storage_path() . '/app/geoip.mmdb');
  $record = $reader->city($ip);
  dd([
      'ip' => $ip,
      'iso_code' => $record->country->isoCode,
      'country' => $record->country->name,
      'city' => $record->city->name,
  ]);`
But I get AddressNotFoundException exception when testing with this IP=73.124.136.133 and sometimes it returns the correct results.

**Comment by nag381** [comment]
For testing, I have created a test route and I'm passing the IP as a request parameter. I know I can catch the exception and I am doing it in my main function. 
The issue is that GeoIp2\Database\Reader sometimes returns AddressNotFoundException for the same IP used other times it works fine.

**Comment by nag381** [comment]
e.g if i use this IP 109.153.196.23 in lookup, it will return the correct result but if request again, it will throw AddressNotFoundException.

**Comment by oschwald** [comment]
I see. I don't know why that would happen and we haven't received reports of similar behavior. I assume the database used in the test is static and not changing between runs.

Do you have a way that this can be reliably reproduced?

**Comment by nag381** [comment]
It's a very weird behaviour and I am also confused about this. It only happens in my live environment. Locally it works fine. I am using the same geoip.mmdb on live and on dev. 

Can I share with you the geoip.mmdb I am using?
The test route is public. I can share the link to the test route?

**Comment by oschwald** [comment]
Please don't publicly share the database.

On production are you using some sort of caching to try to persist the database reader between requests, e.g., `apc`? Something along those lines is the primary thing that I can think of.

Are you using the C extension in either case?

**Comment by nag381** [comment]
This is just a test route. The database is protected and cannot be accessed publicly.

This the function that returns on the route shared.
`if($request->ip) {
            $ip = $request->ip;
            $path = storage_path('app/geoip.mmdb');
            if(is_file($path)) {
              try {
                $reader = new Reader($path);
                $record = $reader->city($ip);
                return response()->json([
                    'path' => $path,
                    'ip' => $ip,
                    'iso_code' => $record->country->isoCode,
                    'country' => $record->country->name,
                    'city' => $record->city->name,
                ]);
              } catch (AddressNotFoundException $ex) {
                  return 'IP Address Not Found in Database';
              }
            }else {
                return 'No file found';
            }
        }`

No I am not using the C extension.

**Comment by nag381** [comment]
Sorry for the trouble. The issue was that we are running multiple servers on AWS and the maxmind db was not all server instances which was causing it to fail sometimes and not all times. We traced this error by printing server instance and checking file_exists.

**Comment by oschwald** [comment]
Good to hear that you found the cause!
