### ISSUE TITLE
Does not play well with PHP Scoper

### ISSUE THREAD

**Issue by andrewjmead** [maxmind/GeoIP2-php#194]
I'm using this library in a WordPress plugin that uses PHP Scoper to scope all dependencies.

I noticed that this library does not support PHP Scoper out of the box due to its use of string class names as seen [here](https://github.com/maxmind/GeoIP2-php/blob/main/src/Database/Reader.php#L228), [here](https://github.com/maxmind/GeoIP2-php/blob/main/src/Database/Reader.php#L239), and [here](https://github.com/maxmind/GeoIP2-php/blob/main/src/WebService/Client.php#L252). 

I was able to patch this in PHP Scoper using the following patcher, but it would be awesome to see built-in support. Keep in mind this just patches the two instances in `Reader.php` and doesn't attempt to patch the instance in `Client.php`:

```
    'patchers' => [
        static function (string $filePath, string $prefix, string $contents): string {
            $parts = explode('vendor', $filePath);

            // Fix an issue with geoip2 where the reader has string class names
            if ($parts[1] === '/geoip2/geoip2/src/Database/Reader.php') {
                return preg_replace(
                    '%\$class = \'GeoIp2%',
                    '$class = \'' . $prefix . '\\\\GeoIp2',
                    $contents
                );
            }

            return $contents;
        },
    ],
```

I was encourage to open a separate issue by @oschwald in #170. Thanks!

😁

**Comment by oschwald** [comment]
Would you be willing to test #195 to confirm that it resolves the issue for you?

**Comment by andrewjmead** [comment]
Yup. I'll test it tomorrow 👍

**Comment by andrewjmead** [comment]
I just installed the branch using `composer require geoip2/geoip2:dev-greg/no-stringy-class-names` and it fixed the issue right away!

**Comment by oschwald** [comment]
Great! Thanks for testing!

**Comment by andrewjmead** [comment]
Thanks to you for addressing it!
