### ISSUE TITLE
Compatibility geoip2 with PHP v8.1 

### ISSUE THREAD

**Issue by lexxai** [maxmind/GeoIP2-php#209]
Deprecated: Return type of GeoIp2\Model\AbstractModel::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in www/wp-content/plugins/wp-statistics/includes/vendor/geoip2/geoip2/src/Model/AbstractModel.php on line 63

Deprecated: Return type of GeoIp2\Record\AbstractRecord::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in www/wp-content/plugins/wp-statistics/includes/vendor/geoip2/geoip2/src/Record/AbstractRecord.php on line 57

https://github.com/wp-statistics/wp-statistics/commit/dafbf2b72e33f1451568ecd24ad1e1fabeefc6cd

https://wordpress.org/support/topic/deprecated-errors-4/

**Comment by oschwald** [comment]
Can you confirm that this happens with 2.13.0? The linked code appears to be at least a few years out of date. I believe this has since been fixed.
