### ISSUE TITLE
Unknown attribute: iso_code

### ISSUE THREAD

**Issue by JustinBack** [maxmind/GeoIP2-php#211]
Encountering this weird issue with the CountryLite.db

I am trying to access the iso_code of the country

with `$Country->country->iso_code`, returning `Unknown attribute: iso_code`

json_encoding `$Country->country` shows the attribute exists

```json
{
	"geoname_id": 2921044,
	"is_in_european_union": true,
	"iso_code": "DE",
	"names": {
		"de": "Deutschland",
		"en": "Germany",
		"es": "Alemania",
		"fr": "Allemagne",
		"ja": "\u30c9\u30a4\u30c4\u9023\u90a6\u5171\u548c\u56fd",
		"pt-BR": "Alemanha",
		"ru": "\u0424\u0420\u0413",
		"zh-CN": "\u5fb7\u56fd"
	}
}
```

anything I am missing here?

**Comment by oschwald** [comment]
The attribute is `isoCode`, not `iso_code`.

**Comment by JustinBack** [comment]
Oh boy, thanks for pointing this out - Just checked the docs again as well and its right there 🤦🏻
