### ISSUE TITLE
Is it possible to get an array of all countries/cities from a country?

### ISSUE THREAD

**Issue by cawa-93** [maxmind/GeoIP2-php#222]
I am wondering if it is possible to get an array of all countries, all cities in a country that are contained in the provided database using this library?

I've looked through the documentation, but didn't find any relevant examples.

**Comment by oschwald** [comment]
No, the data is not organized in a way to make this reasonably possible. I'd suggest either using the CSVs for this or using GeoNames directly.

**Comment by cawa-93** [comment]
It sounds reasonable. My case is to create a UI component for the site administrator that requires data on cities that GeoIP2 can detect. For the same reason, I can't just take the data from GeoName directly, because it seems that GeoName has more entities than your set.
I don't need to read them in the runtime. I can easily read the database and generate some JSON at the build step. So performance is not an issue at all.

Of course, I can get the data I need from CSV, but I would really like to keep a single source of truth. Maybe I can somehow `getAllIterator()` to foreach all entities in database and collect all needed data from it?
