### ISSUE TITLE
geoip2.phar sometimes does a wrong platform / PHP version check

### ISSUE THREAD

**Issue by mdrmdrmdr** [maxmind/GeoIP2-php#227]
I'm running `geoip2.phar` V3.0.0 in a web hoster environment with currently **PHP 8.3.6**.
In >99.99% of all uses, it works fine. But sometimes, this error pops up:

```
Fatal error: Composer detected issues in your platform:
Your Composer dependencies require a PHP version ">= 8.1.0“.
You are running 7.2.34.
in phar://<document-root>/scripts/GeoIp2/geoip2.phar/vendor/composer/platform_check.php on line 24
```
I have no idea what causes this.

It has to be said, that the hoster environment has a fall back to the system default PHP version, which currently is 7.2.34, if a sub-process is created. For example `shell_exec` in PHP.

Why does `geoip2.phar` _sometimes_ start a sub-process and most of the times not? Or is there any other issue causing the error?

**Comment by oschwald** [comment]
The Phar file is loaded into whatever process you `require` it from. It sounds like that process is sometimes an older version of PHP. It does not start a new PHP process itself.

**Comment by mdrmdrmdr** [comment]
Guess you're right. I call the `require`'ing PHP from Perl with `php <script>` (using backticks ``), trusting the proper path resolution of the system. Which obviously does not work always. Now I changed the call to use `/usr/bin/php83` explicitly. Hope this avoids the above described behavior.

**Comment by oschwald** [comment]
Thanks for confirming. I'll close this out.
