### ISSUE TITLE
Calling Reader::country() returns null with City database

### ISSUE THREAD

**Issue by daigo75** [maxmind/GeoIP2-php#47]
I'm working on a project where we are required to geolocate visitors' country and, in some cases, visitors' city as well. Due to that, I switcher from the Country database to the City one, but I encountered an unexpected behaviour, described below:

~~~
$reader = new Reader('GeoLite2-Country.mmdb');
$country = $reader->country('87.65.122.63')->isoCode; // This returns "BE - Belgium"

$reader = new Reader('GeoLite2-City.mmdb');
$country = $reader->country('87.65.122.63')->isoCode; // This returns false
~~~

Questions
--
1. Is such behaviour correct? I thought that the City database could be used for **both** Country and City detection.
2. Our target is to always detect the country and, if possible, the city. If the City database can only be used for city detection, what happens if such information cannot be determined? For example, if I pass an IP Address and the city cannot be determined, how do I get the country from it?

**Comment by oschwald** [comment]
On recent versions of this library, calling `$reader->country(...)` with a City database should throw a `BadMethodCallException`. Use the `city()` method instead.

For instance, this works for me:

```
$reader = new Reader("/usr/local/share/GeoIP/GeoLite2-City.mmdb");
echo $reader->city('87.65.122.63')->country->isoCode;
```

**Comment by daigo75** [comment]
That's correct, if I use `city` and then `country` it works. However, I'm worried about what would happen if the city cannot be determined. Do I still get a record with a country object?

**Comment by oschwald** [comment]
The methods on the reader object are for the database type, not the field type. Using the city method will return any data that is in the City database for that IP.

**Comment by daigo75** [comment]
I see. If I understand it correctly, I will get all the information available for the IP address, which means:
- If a city is available, I will get its details. I will also get the country details.
- If a city is **not** available, I will still get the country details, as part of the returned record.

Is that correct?

**Comment by oschwald** [comment]
Yes.

**Comment by daigo75** [comment]
Perfect, thanks.
