### ISSUE TITLE
Create Phar files with documentation intact

### ISSUE THREAD

**Issue by DomBlack** [maxmind/GeoIP2-php#52]
The current phar file has zero documentation within it.

This means ID's get very confused when you are trying to use the models as either it cannot find what you are asking for, or thinks your accessing a private method.

If the phar file shipped with it's PHPdoc still present, this issue would be resolved.

![screen shot 2015-09-08 at 14 47 55](https://cloud.githubusercontent.com/assets/236641/9736377/ae52ece2-5638-11e5-8322-e7118534f168.png)

**Comment by oschwald** [comment]
Thanks for bringing this up. It should be fixed in our next release.
