### ISSUE TITLE
GeoIp2 and legacy format

### ISSUE THREAD

**Issue by Ragazzo** [maxmind/GeoIP2-php#60]
In legacy format we had `$location->region` attribute, is this attribute represented in new GeoIp2 client? If compared to `mostSpecificSubdivision` i would not say it is the same, because identities (id) are not the same as for legacy.

**Comment by oschwald** [comment]
FIPS regions, which are used in GeoIP Legacy, are not included in GeoIP2. GeoIP2 only includes ISO subdivisions. See [this page](http://dev.maxmind.com/geoip/geoip2/whats-new-in-geoip2/) for a list of differences between the two formats.

**Comment by Ragazzo** [comment]
Ok, we figured it out and now use them, anyway thank you

**Comment by stafot** [comment]
> Ok, we figured it out and now use them, anyway thank you

@Ragazzo Could you provide more info? Did you find a way to use regions or you extracted region info from subdivision?
