### ISSUE TITLE
Slow lookups

### ISSUE THREAD

**Issue by SimonDeconde** [maxmind/GeoIP2-php#61]
Hi there

I've been comparing this library to the legacy geoip-api-php (https://github.com/maxmind/geoip-api-php) in terms of lookup speed.
I've read that the new format (.mmdb) is supposed to offer faster lookups than the old format (.dat), however my tests show the opposite, with way slower lookups.

Consider the below code: 
```php
use GeoIp2\Database\Reader;

function ip_lookup_geoip($ip) {
  $geoip_old_reader = geoip_open(realpath('.').'/sites/all/libraries/GeoLiteCity.dat', GEOIP_STANDARD);
  $record = geoip_record_by_addr($geoip_old_reader, $ip);
  geoip_close($geoip_old_reader);
  return $record;
}

function ip_lookup_geoip2($ip) {
  $geoip_reader = new Reader(realpath('.').'/sites/all/libraries/GeoLite2-City.mmdb');
  
  try {
    $record = $geoip_reader->city($ip);
    return $record;
  } catch (Exception $e) {
    print('An error happened while looking up IP !ip: '.$e->getMessage());
  }

  return FALSE;
}

$ip = '173.194.115.23';

$start = microtime(TRUE);
$record = ip_lookup_geoip($ip);
$elapsed = microtime(TRUE) - $start;
print("[geoip] Lookup time: $elapsed\r\n");
print("[geoip] $ip: {$record->country_name} > {$record->city}\r\n");

$start = microtime(TRUE);
$record = ip_lookup_geoip2($ip);
$elapsed = microtime(TRUE) - $start;
print("[geoip2] Lookup time: $elapsed\r\n");
print("[geoip2] $ip: {$record->country->name} > {$record->city->name}\r\n");
```

**Execution trace:**
```
[geoip] Lookup time: 0.0038161277770996
[geoip] 173.194.115.23: United States > Mountain View
[geoip2] Lookup time: 0.14523100852966
[geoip2] 173.194.115.23: United States > Mountain View
```

Am I missing something here?

**Comment by oschwald** [comment]
I wouldn't say you are missing anything, but there are a couple of ways to improve performance:

* Use the [C extension](https://github.com/maxmind/MaxMind-DB-Reader-php/#optional-php-c-extension).
* Do not open the database for every lookup. Most of the time in your benchmarks is likely spent finding and reading in the metadata.

**Comment by SimonDeconde** [comment]
Hi Oschwald

Thanks for your reply.

My example code was written for simplicity, but even without opening/closing the database for every lookup the performance difference can be seen. 
Based on both 1) a more advanced benchmark (2000 ip lookup loops) and 2) a real application where I import visitor geolocation (millions of lookups), I'm still seeing a 3x slower lookup time than with the legacy library.
I've indeed heard about the C extension, but I wanted to compare the two libraries/formats based on pure-PHP solutions.

Based on your experience, is that normal that this library is slower than the legacy one? If so, is there a specific technical reason?

Considering the C extension, would you say that this new library + C extension is faster than the old library + C extension?

Thanks for your help!

**Comment by oschwald** [comment]
Yes, it is expected that the new format will be slower. The new database contains quite a bit more information that gets read out of the database during the request and the search tree is deeper as the new format supports IPv6 in the same database as IPv4. Although we did not provide a C extension ourselves for the old format, I would suspect that the PECL one for the old format is also faster than the official extension for the new format.

**Comment by SimonDeconde** [comment]
Thanks for the details Gregory!
