### ISSUE TITLE
Documentation update - PHAR requirements and common issues

### ISSUE THREAD

**Issue by cfv1000** [maxmind/GeoIP2-php#78]
Hello,
I had some issues trying to implement the PHAR on my production server. I finally managed to fix it by reading the PHPUnit documentation about phar implementation and requirements

![image](https://cloud.githubusercontent.com/assets/3073353/18195985/76dbc83a-70f7-11e6-8f43-4726e648460d.png)

Could you please update your documentation to include more details about this? 
Thanks

**Comment by oschwald** [comment]
Which issue did you have and what error did you receive?

**Comment by cfv1000** [comment]
I was unable to load the library in my project. I kept getting a 500 error, with no error messages in error log.

**Comment by nulledcc** [comment]
This is not mmdb Error this is phpunit test service error, maybe you had set php-debugger so it throws this error.
