### ISSUE TITLE
T_CONSTANT_ENCAPSED_STRING on `use GeoIp2\WebService\Client;`

### ISSUE THREAD

**Issue by carlosfcocruz** [maxmind/GeoIP2-php#86]
It works on my local environment, but when I deploy to my server, I'm getting `T_CONSTANT_ENCAPSED_STRING`. Any tips ?

**Comment by oschwald** [comment]
It sounds like there is a syntax error in the calling code. Could you provide that?

Also, what version of PHP is on the server?

**Comment by oschwald** [comment]
I am closing this as I cannot reproduce it without more information.
