### ISSUE TITLE
Discrepency in API regarding Insights get information

### ISSUE THREAD

**Issue by rperdon** [maxmind/GeoIP2-php#88]
Looking at pulling the some data down and while some work, some do not.

Example: 
$record->subdivisions->names
$record->subdivisions->names->en
$record->subdivisions->names[en]

Returns "" (nothing). No errors in the log.

If I pull the "subdivisions" array and convert the set to JSON, I get this back:

echo json_encode($record->subdivisions, JSON_UNESCAPED_UNICODE);
returns:
[{"confidence":60,"iso_code":"BY","geoname_id":2951839,"names":{"ru":"Бавария","zh-CN":"巴伐利亚","de":"Bayern","en":"Bavaria","es":"Baviera","fr":"Bavière","ja":"バイエルン州","pt-BR":"Baviera"}}]

Looking at the traits php file, I see that the "types" exist in the file, yet when I make the calls, I get nothing back. So I know the data is there but I am unable to retrieve it via the API code correctly when  "names" is referenced.

Also looking into the php file and the reported output, there is a discrepancy in the naming versus the Dev maxmind site. 

ie Subdivisions (which is subdivision.php and subdivision namespace). 
http://dev.maxmind.com/geoip/geoip2/web-services/#subdivisions
object names such as userType when its referred on the web as  user_type 

This is a trivial matter but it makes referencing the maxmind page a bit troublesome as what you read there may not be how you access it in code. This also causes a bit of problem when the array you retrieve specifically returns "user_type" but to make the call to it you must use userType.

ie
$record->traits->userType

if printing out record->traits:
{"user_type":"hosting","autonomous_system_number":24940,"autonomous_system_organization":"Hetzner Online GmbH","domain":"your-server.de","isp":"Hetzner Online GmbH","organization":"Hetzner Online AG","ip_address":"78.46.100.73"}

**Comment by oschwald** [comment]
I am a bit confused. The example code you provide is wrong. `->subdivisions` is an array, not an object. PHP will return a notice like:

```
PHP Notice:  Trying to get property of non-object...
```

As for your naming comment, the model classes use the standard PHP naming conventions as specified by the PSR-2 style guidelines. Please see the [PHP API docs](http://maxmind.github.io/GeoIP2-php/doc/v2.4.4/).
