### ISSUE TITLE
Caching options

### ISSUE THREAD

**Issue by BassemN** [maxmind/GeoIP2-php#90]
Hello,

Thanks for this awesome library.
I'd like to see more caching options to accelerate lookup speed like caching the database file into memory using shmop PHP extension.

Thanks

**Comment by oschwald** [comment]
The pure PHP reader is file based, not memory based. It would need significant changes to support loading the file into memory like this. However, you generally should be using the C extension in production environments anyway.

For the C extension, there is https://github.com/maxmind/MaxMind-DB-Reader-php/issues/36 for allowing the database to remain open between requests.

For either of these, the change would be in `MaxMind\Db`, not `GeoIp2`. Please open an issue at https://github.com/maxmind/MaxMind-DB-Reader-php/issues or add to an existing one like the one above.

**Comment by BassemN** [comment]
@oschwald  Thank you, I'll open an issue there.

**Comment by oschwald** [comment]
Thanks!
