### ISSUE TITLE
No docs for available object in database! 

### ISSUE THREAD

**Issue by Anan5a** [maxmind/GeoIP2-php#91]
I've downloaded the country database but didn't found anything which will guide me about the data structure in database :(
I tried ```php
...
$record=$reader->country("118.90.116.80");
echo $record->isoCode;
```
and it thrown error!
Please help

**Comment by oschwald** [comment]
There are API docs available at http://maxmind.github.io/GeoIP2-php/doc/v2.4.5/class-GeoIp2.Database.Reader.html
