### ISSUE TITLE
not able to access mostSpecificSubdivision values

### ISSUE THREAD

**Issue by amolbarewar** [maxmind/GeoIP2-php#92]
if(isset($record->mostSpecificSubdivision) && !empty($record->mostSpecificSubdivision->names) )) {
....
}

when I do var_dump($record->mostSpecificSubdivision) then I am getting an object displayed but when I check for this property using empty() and isset() then I am getting false response.

**Comment by oschwald** [comment]
What version are you using? This was fixed in [2.4.4](https://github.com/maxmind/GeoIP2-php/blob/master/CHANGELOG.md#244-2016-10-11).

**Comment by bradleyhodges** [comment]
I'm running 2.9.0 and this is still a problem.

**Comment by nchelluri** [comment]
Hi bradleyhoges, can you post the IP you are looking up, the name of the database file you are using, and your code?

**Comment by simonberger** [comment]
I was about to report the same problem.
But I noted this entry has no translation for my requested locale. My step now was to always add english as a second fallback locale. An (optional) automatic functionality that would make sense in the framework as well. A non-native returned value is always better than none.

Tested IP was 87.101.146.176.
This entry lacks a city I just wanted to test the most specific subdivision.
